### ISSUE TITLE
Invalid move refresh

### ISSUE THREAD

**Issue by 0rr** [TeamFinishers/chessapp#25]
When a user moves a piece in an invalid way during a game, the page refreshes. After that refresh, the piece which the user attempted to move in an invalid fashion is back in its immediately prior location - all good. However, there is also another (extra) piece populated in the original starting position.

**Comment by bkichler** [comment]
Pieces are getting created twice, on game create and when a player joins. Will deal with this by removing piece creation from join_as_color methods in game controller.
